### PR TITLE
Phase 2: Distributed Energy weekly enl setup

### PR DESCRIPTION
**Pull request by Alixers505**
https://www.pivotaltracker.com/story/show/171654082

Phase 2: Layout changes

DTE-weekly-enl

### CODE REVIEW

**Comment by Alixers505** [comment]
@B77Mills or @CaitlynKnudsvig - could one of y'all pick this up and release it this week? It's been sitting for a while now.

**Comment by CaitlynKnudsvig** [comment]
Did Alex or Deb approve the new style yet?  We might want to consider matching the appearance of the existing templates for when we we migrate all the other groups to the new framework, @brandonbk - what do you think?

**Comment by Alixers505** [comment]
> Did Alex or Deb approve the new style yet? We might want to consider matching the appearance of the existing templates for when we we migrate all the other groups to the new framework, @brandonbk - what do you think?

@CaitlynKnudsvig - I've requested a review again. However, they won't be able to verify it on the newsletters preview site until these phase 2 changes go live.

**Comment by CaitlynKnudsvig** [comment]
Sounds like Deb is cool with pushing this live for testing and circling back to make changes later, so I'll merge/deploy this as-is

**Pull request merged**
